spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: devfedi1337@gmail.com
    password: mlco zfcv zbwu bflj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://localhost:3306/kdg?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
server:
  port: 8081
application:
  security:
    jwt:
      secret-key: 04705BBC0CDDB30BA09FB9DDCBE4461D9A6C667CD20BD4AADC48513BF6D39AE2
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days